Whitecat
jacjjao/BattleCat pull request #18
Opened 2024-03-04 14:49 UTC by Whitecatuwu

新增按鈕文字(圖片，原版遊戲也是圖片實現)
(註:目前找不到"遊戲開始"文字)
修改gamebutton，現在能用建構子建構

2024-03-05 00:09 UTC, jacjjao requested changes
按鈕音效不能寫死

2024-03-05 00:09 UTC, jacjjao commented on include/GameButton.hpp
> +    };
在戰鬥時派出貓咪和升級工作狂貓的按鈕聲音和一般的按鈕不太一樣。

2024-03-05 00:24 UTC, jacjjao requested changes
如comment

2024-03-05 00:24 UTC, jacjjao commented on src/GameButton.cpp
> +}
這樣會導致所有GameButton instance的點擊音效都一樣，而且一改是改所有的instance而不是單一一個button，member function的功能理應是只修改呼叫該function的instance才對。

2024-03-05 15:09 UTC, Whitecatuwu commented
增加cat base "開始按鈕、升級按鈕、隊伍編成按鈕"(還未添加文字與函數)
修改了上述gamebutton的問題

2024-03-06 00:58 UTC, jacjjao approved these changes

2024-03-06 00:58 UTC, merged